name: ci-golang-workflow-study
on: [push]
jobs:
  check-application-golang:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24.2
      - run: go test
      - run: go run math.go