name: ci-golang-workflow-study
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24.2
      - run: go test
      - run: go run math.go