name: ci-golang-workflow-study
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application-golang:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        go: [ '1.23', '1.24.2' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24.2
      #        with:
#          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go

      - name: Setup QEMU container
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false # realizar o push na imagem
          tags: igor-pedro/app-pipeline:latest # nome da imagem